#!/usr/bin/env node
/**
 * Render the site's mark into every place a browser or a link preview looks
 * for it: the favicon, the legacy favicon.ico, the iOS touch icon, and the
 * social card.
 *
 * ONE SOURCE. The geometry is apps/web/lib/mark.ts, which the site's header
 * and footer import as a component. This imports the same file (Node strips
 * the types), so the favicon and the header cannot drift into two different
 * marks. The colours and font stacks are read out of apps/web/styles/globals.css
 * rather than restated, for the same reason.
 *
 * WHY A BROWSER. The PNGs need text in the site's own type, and the site's type
 * is the system stack in globals.css: no web font is loaded, because the CSP
 * forbids off-origin loads and a self-hosted font is weight nobody needs for a
 * documentation site. Chrome lays that stack out exactly as a reader's browser
 * does. The images are committed, because Vercel builds without a browser.
 *
 * WHAT --check COMPARES, and what it cannot. Chrome rasterises text through
 * CoreText on macOS and FreeType on Linux (gen-device-shots found this out on
 * its first CI run), so re-rendering and comparing pixels would fail on every
 * machine but the one that made the images. The question this answers is
 * whether the images are stale, and that needs no browser:
 *
 *   1. icon.svg is text, so it is regenerated and compared byte for byte.
 *   2. The hash of the exact pages the PNGs are photographs of, which carry
 *      the mark's geometry, the tokens read from globals.css and the card's
 *      layout, must equal the hash recorded when they were rendered. The
 *      pages, not the source files, so a reworded comment is not a stale
 *      image and a changed colour token is.
 *   3. Each PNG must still be the file that was rendered, by its own hash, so
 *      one replaced by hand is caught too, and must have the size the page
 *      metadata declares.
 *
 * Run: node tools/gen-brand.mjs [--check]
 * Needs: Chrome, to render. Set CHROME_PATH to override. --check needs neither.
 */

import { spawn } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { GLYPH_VIEWBOX, MARK, markSvg } from '../apps/web/lib/mark.ts'
import {
  chromeBinary,
  chromeProfile,
  finish,
  freePort,
  reap,
  waitForDebugEndpoint,
} from './lib/browser.mjs'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const WEB = join(ROOT, 'apps/web')
const CSS = join(WEB, 'styles/globals.css')
const STAMP = join(WEB, 'public/brand/rendered-from.json')
const check = process.argv.includes('--check')

/* --- The site's own tokens ------------------------------------------------ */

const css = readFileSync(CSS, 'utf8')
function token(name) {
  const match = new RegExp(`--${name}:\\s*([^;]+);`).exec(css)
  if (match === null) {
    console.error(`gen-brand: globals.css no longer defines --${name}.`)
    process.exit(1)
  }
  return match[1].replace(/\s+/g, ' ').trim()
}
const T = {
  ink950: token('color-ink-950'),
  ink800: token('color-ink-800'),
  ink500: token('color-ink-500'),
  ink400: token('color-ink-400'),
  ink100: token('color-ink-100'),
  signal: token('color-signal-500'),
  mono: token('font-mono'),
  sans: token('font-sans'),
}

/* --- What gets written ---------------------------------------------------- */

const ICON_SVG = join(WEB, 'app/icon.svg')
const iconSvg = markSvg({ background: T.ink950, foreground: T.signal }).replace(
  '\n',
  '\n  <!-- Generated by tools/gen-brand.mjs from apps/web/lib/mark.ts. Edit that\n' +
    '       file and run "make brand", not this one. Drawn rather than fetched,\n' +
    '       because the CSP forbids loading anything off-origin. -->\n'
)

/**
 * The raster images, each with the size the page metadata declares for it.
 *
 * The touch icon is square: iOS applies its own rounded mask, and a rounded
 * tile inside that mask shows dark corners. favicon.ico sits in public/ rather
 * than app/, because Next marks an app/favicon.ico as `sizes="any"`, which puts
 * it in competition with icon.svg in browsers that can use the SVG. From
 * public/ it is only what older browsers find by asking for /favicon.ico.
 */
const PNGS = [
  { file: 'app/apple-icon.png', width: 180, height: 180, html: () => iconPage(true) },
  { file: 'public/brand/og.png', width: 1200, height: 630, html: cardPage },
]
const ICO = { file: 'public/favicon.ico', sizes: [16, 32, 48] }

/* --- The pages the images are photographs of ------------------------------ */

const svgData = (svg) => `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`

function iconPage(square) {
  const svg = markSvg({ background: T.ink950, foreground: T.signal, square })
  return `<!doctype html><html><head><style>
    html, body { margin: 0; background: transparent; }
    img { display: block; width: 100vw; height: 100vh; }
  </style></head><body><img src="${svgData(svg)}" alt=""></body></html>`
}

/**
 * The social card: the mark and the name, the headline, and what the thing is.
 *
 * The same words the home page opens with and nothing added, because a link
 * preview is the site speaking about itself where the threat model is not
 * beside it to qualify anything. The wash is the hero's, at the hero's
 * strength.
 */
function cardPage() {
  const { ring, slash, stroke } = MARK
  const glyph =
    `<svg viewBox="${GLYPH_VIEWBOX}" width="44" height="44" fill="none" stroke="${T.signal}" ` +
    `stroke-width="${String(stroke)}" stroke-linecap="round">` +
    `<circle cx="${String(ring.cx)}" cy="${String(ring.cy)}" r="${String(ring.r)}"/>` +
    `<line x1="${String(slash.x1)}" y1="${String(slash.y1)}" x2="${String(slash.x2)}" y2="${String(slash.y2)}"/></svg>`
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><style>
    html, body { margin: 0; width: 1200px; height: 630px; overflow: hidden; }
    body {
      box-sizing: border-box;
      padding: 76px 88px 84px;
      display: flex; flex-direction: column; justify-content: space-between;
      background:
        radial-gradient(70% 60% at 50% 0%, color-mix(in srgb, ${T.signal} 6%, transparent) 0%, transparent 70%),
        ${T.ink950};
      color: ${T.ink100};
      font-family: ${T.sans};
      -webkit-font-smoothing: antialiased;
    }
    .top { display: flex; align-items: center; justify-content: space-between; }
    .name { display: flex; align-items: center; gap: 16px; }
    .word { font-family: ${T.mono}; font-size: 34px; font-weight: 600; letter-spacing: -0.02em; }
    .host { font-family: ${T.mono}; font-size: 20px; color: ${T.ink500}; }
    h1 {
      margin: 0; font-size: 84px; line-height: 1.04; font-weight: 600; letter-spacing: -0.03em;
    }
    .rule { margin-top: 44px; border-top: 1px solid ${T.ink800}; padding-top: 28px; }
    .what {
      font-family: ${T.mono}; font-size: 19px; text-transform: uppercase;
      letter-spacing: 0.22em; color: ${T.ink400};
    }
  </style></head><body>
    <div class="top">
      <div class="name">${glyph}<span class="word">nullroute</span></div>
      <span class="host">nullroute.diy</span>
    </div>
    <div>
      <h1>Built to be checked,<br>not to be trusted.</h1>
      <div class="rule"><span class="what">Air-gapped Bitcoin signer for the Raspberry Pi</span></div>
    </div>
  </body></html>`
}

/* --- The stamp ------------------------------------------------------------ */

const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex')
const source = sha256(
  JSON.stringify([
    ...PNGS.map((png) => [png.file, png.width, png.height, png.html()]),
    [ICO.file, ICO.sizes, iconPage(false)],
  ])
)

/** Width and height from a PNG's IHDR, which is always the first chunk. */
function pngSize(bytes) {
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) }
}

/**
 * An ICO holding PNGs. Every browser that still asks for favicon.ico reads
 * PNG entries, and it keeps this to a header and a directory rather than a
 * bitmap encoder.
 */
function ico(images) {
  const header = Buffer.alloc(6 + 16 * images.length)
  header.writeUInt16LE(0, 0)
  header.writeUInt16LE(1, 2)
  header.writeUInt16LE(images.length, 4)
  let offset = header.length
  images.forEach(({ size, bytes }, i) => {
    const at = 6 + 16 * i
    header.writeUInt8(size >= 256 ? 0 : size, at)
    header.writeUInt8(size >= 256 ? 0 : size, at + 1)
    header.writeUInt16LE(1, at + 4)
    header.writeUInt16LE(32, at + 6)
    header.writeUInt32LE(bytes.length, at + 8)
    header.writeUInt32LE(offset, at + 12)
    offset += bytes.length
  })
  return Buffer.concat([header, ...images.map((image) => image.bytes)])
}

/* --- --check -------------------------------------------------------------- */

function runCheck() {
  const problems = []
  const rel = (path) => relative(ROOT, path)

  if (!existsSync(ICON_SVG) || readFileSync(ICON_SVG, 'utf8') !== iconSvg) {
    problems.push(`${rel(ICON_SVG)} is not what apps/web/lib/mark.ts draws`)
  }

  const stamp = existsSync(STAMP) ? JSON.parse(readFileSync(STAMP, 'utf8')) : null
  if (stamp === null) {
    problems.push(`${rel(STAMP)} is missing, so nothing records what the images were drawn from`)
  } else {
    if (stamp.source !== source) {
      problems.push(
        `the mark, the site's tokens or the card layout changed after the images were rendered ` +
          `(rendered from ${String(stamp.source).slice(0, 16)}, source is now ${source.slice(0, 16)})`
      )
    }
    for (const item of [...PNGS, { file: ICO.file }]) {
      const path = join(WEB, item.file)
      if (!existsSync(path)) {
        problems.push(`apps/web/${item.file} is missing`)
        continue
      }
      const bytes = readFileSync(path)
      if (stamp.files?.[item.file] !== sha256(bytes)) {
        problems.push(`apps/web/${item.file} is not the file that was rendered`)
      }
      if ('width' in item) {
        const got = pngSize(bytes)
        if (got.width !== item.width || got.height !== item.height) {
          problems.push(
            `apps/web/${item.file} is ${String(got.width)}x${String(got.height)}, ` +
              `the metadata says ${String(item.width)}x${String(item.height)}`
          )
        }
      }
    }
  }

  if (problems.length > 0) {
    console.error('gen-brand: the committed icons and social card are stale.\n')
    for (const problem of problems) console.error(`  ${problem}`)
    console.error('\n  Regenerate with "make brand" and look at the images before committing.\n')
    process.exit(1)
  }
  console.log(
    `gen-brand: icon.svg matches the mark, and ${String(PNGS.length + 1)} raster images were ` +
      `rendered from this exact source (${source.slice(0, 16)}). Pixels are not re-rendered ` +
      `here: see the header of tools/gen-brand.mjs.`
  )
}

/* --- Rendering ------------------------------------------------------------ */

const seq = { id: 0 }
function cdp(ws, method, params = {}) {
  return new Promise((resolve, reject) => {
    const id = (seq.id += 1)
    const onMessage = (event) => {
      const msg = JSON.parse(event.data)
      if (msg.id !== id) return
      ws.removeEventListener('message', onMessage)
      if (msg.error) reject(new Error(`${method}: ${msg.error.message}`))
      else resolve(msg.result)
    }
    ws.addEventListener('message', onMessage)
    ws.send(JSON.stringify({ id, method, params }))
  })
}

async function render() {
  const debug = await freePort()
  const chrome = spawn(
    chromeBinary('gen-brand'),
    [
      '--headless',
      '--disable-gpu',
      '--no-sandbox',
      '--disable-dev-shm-usage',
      '--hide-scrollbars',
      `--remote-debugging-port=${String(debug)}`,
      chromeProfile('gen-brand'),
      'about:blank',
    ],
    { stdio: ['ignore', 'pipe', 'pipe'] }
  )
  const browser = new WebSocket(await waitForDebugEndpoint(chrome, debug))
  await new Promise((r) => browser.addEventListener('open', r, { once: true }))
  const { targetId } = await cdp(browser, 'Target.createTarget', { url: 'about:blank' })
  const targets = await (await fetch(`http://127.0.0.1:${String(debug)}/json/list`)).json()
  const page = new WebSocket(targets.find((t) => t.id === targetId).webSocketDebuggerUrl)
  await new Promise((r) => page.addEventListener('open', r, { once: true }))
  await cdp(page, 'Page.enable')
  // Transparent, so the favicon's rounded corners are corners and not ink.
  await cdp(page, 'Emulation.setDefaultBackgroundColorOverride', {
    color: { r: 0, g: 0, b: 0, a: 0 },
  })

  async function shoot(html, width, height) {
    await cdp(page, 'Emulation.setDeviceMetricsOverride', {
      width,
      height,
      deviceScaleFactor: 1,
      mobile: false,
    })
    const loaded = new Promise((resolve) => {
      const onMessage = (event) => {
        if (JSON.parse(event.data).method !== 'Page.loadEventFired') return
        page.removeEventListener('message', onMessage)
        resolve()
      }
      page.addEventListener('message', onMessage)
    })
    await cdp(page, 'Page.navigate', {
      url: `data:text/html;base64,${Buffer.from(html).toString('base64')}`,
    })
    await loaded
    // Load fires before system fonts are guaranteed to be laid out.
    await cdp(page, 'Runtime.evaluate', { expression: 'document.fonts.ready', awaitPromise: true })
    const shot = await cdp(page, 'Page.captureScreenshot', {
      format: 'png',
      clip: { x: 0, y: 0, width, height, scale: 1 },
    })
    return Buffer.from(shot.data, 'base64')
  }

  const files = {}
  const write = (file, bytes) => {
    const path = join(WEB, file)
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, bytes)
    files[file] = sha256(bytes)
  }

  try {
    for (const png of PNGS) write(png.file, await shoot(png.html(), png.width, png.height))
    const entries = []
    for (const size of ICO.sizes)
      entries.push({ size, bytes: await shoot(iconPage(false), size, size) })
    write(ICO.file, ico(entries))
  } finally {
    page.close()
    browser.close()
    reap(chrome)
  }

  writeFileSync(ICON_SVG, iconSvg)
  mkdirSync(dirname(STAMP), { recursive: true })
  writeFileSync(
    STAMP,
    `${JSON.stringify({ source, platform: `${process.platform}-${process.arch}`, files }, null, 2)}\n`
  )
  console.log(
    `gen-brand: wrote app/icon.svg, ${Object.keys(files).join(', ')} under apps/web from ${source.slice(0, 16)}`
  )
}

if (check) {
  runCheck()
  finish(0)
} else {
  render()
    .then(() => finish(0))
    .catch((err) => {
      console.error(`gen-brand: ${err.message}`)
      finish(1)
    })
}
