import type { Facts } from '../../lib/facts'

/**
 * The first screen, and the argument in miniature.
 *
 * THE DICE DEMO USED TO BE HERE, in the right column, and it answered the wrong
 * question. A visitor who has never heard of this arrives asking what the thing
 * IS, and the first interactive object on the page was a grid of dice buttons
 * next to the headline. That reads as the product: a web page where you roll
 * dice. It is not. The product is a Raspberry Pi with no network, and the demo
 * is a small proof about one arithmetic step inside it.
 *
 * So the space goes to the device itself, on its own panel, showing the number
 * this whole project is arranged around. Someone who looks at it for two
 * seconds knows what is being offered and where it runs. The demo moved to the
 * section about checking and then went altogether: it read as an app there
 * too, and a printed command with its expected digest makes the same point.
 *
 * There are no buttons here on purpose. A pair of accented calls to action is
 * the grammar of a page trying to convert a visitor, and this page is not.
 * Someone who wants the source will find the link in the header.
 *
 * A three.js scene used to occupy the right half before the demo did. Its own
 * comment conceded it was a diagram of something the prose already said, and it
 * cost a dependency, a WebGL context and about 350 lines to say it. This is a
 * photograph of the real frontend instead, generated by `make device-shots`
 * from the same gallery the layout and contrast checks measure, and
 * `make device-shots-check` fails the build when it stops matching.
 */
export function Hero({ facts }: { facts: Facts }) {
  return (
    <section className="relative pt-16 pb-14 sm:pt-24 sm:pb-20">
      {/* A wash rather than a picture. An arbitrary Tailwind value, compiled
          into the stylesheet, so no inline style reaches the CSP.

          THE SECTION IS FULL WIDTH AND THE COLUMN IS INSIDE IT. This used to be
          the other way round, with the wash escaping a max-w-5xl parent via
          `left-1/2 -translate-x-1/2 w-screen`, and that is a bug rather than a
          style: 100vw counts the vertical scrollbar and the content box does
          not. On every page long enough to scroll, the wash was 8px wider than
          the viewport and the whole document scrolled sideways at 768px, 1024px,
          1280px and 1600px. check-responsive measures 320px and 390px, where
          mobile emulation uses overlay scrollbars and the gap is exactly zero,
          so the one bug it exists to catch was invisible to it.

          Inverting the nesting removes the viewport unit instead of correcting
          it. `inset-0` on a full-width section is the content width by
          construction, whatever the scrollbar is doing. */}
      <div aria-hidden="true" className="absolute inset-0 -z-10 overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(70%_60%_at_50%_0%,color-mix(in_srgb,var(--color-signal-500)_6%,transparent)_0%,transparent_70%)]" />
        <div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-ink-950 to-transparent" />
      </div>

      <div className="relative mx-auto max-w-5xl px-5">
        <p className="font-mono text-xs uppercase tracking-[0.22em] text-ink-500">
          Air-gapped Bitcoin signer
        </p>

        {/* Both lines at full contrast. Dimming the second half would fade the
            half that carries the stance; the line break does that work. */}
        <h1 className="mt-5 text-[2.5rem] leading-[1.05] sm:text-6xl sm:leading-[1.03] font-semibold tracking-[-0.03em] text-ink-100 max-w-3xl">
          Built to be checked,
          <span className="block">not to be trusted.</span>
        </h1>

        <div className="mt-9 lg:mt-12 grid gap-10 lg:grid-cols-[minmax(0,1fr)_28rem] lg:gap-14 lg:items-start">
          <div className="min-w-0">
            <p className="text-lg sm:text-xl text-ink-300 leading-relaxed">
              A Raspberry Pi that turns dice into a seed and signs transactions with no network of
              any kind: not for updates, not for fee estimation, not for fonts. Signatures are
              deterministic, so there is nothing random inside one for a key to leak through. Every
              module ships a machine-checkable specification, and the build fails when the code, the
              specs and the tests stop agreeing.
            </p>

            <p className="mt-5 text-lg text-ink-400 leading-relaxed">
              It is one person&rsquo;s build, published because the method is worth arguing with.{' '}
              <span className="text-ink-200">You should not use it.</span> Read it, disagree with
              it, and go build your own.
            </p>

            {/*
              Read out of the verification report at build time, so these are the
              current numbers or the build fails.

              `tests bound to invariants` rather than `exports covered`: the
              coverage check fails the build on any uncovered export, so
              covered/exports is pinned at parity for as long as this site is
              buildable at all. It reads as a measurement and cannot render
              anything but perfection, which is the defect this strip exists to
              avoid. boundTests/tests is gated by nothing and can go down.
            */}
            <dl className="mt-10 flex flex-wrap gap-x-10 gap-y-5 font-mono text-xs">
              {[
                { k: 'specs', v: String(facts.specs) },
                { k: 'invariants', v: String(facts.invariants) },
                {
                  k: 'tests bound to invariants',
                  v: `${String(facts.boundTests)} of ${String(facts.tests)}`,
                },
              ].map((item) => (
                <div key={item.k}>
                  <dt className="uppercase tracking-[0.16em] text-ink-400">{item.k}</dt>
                  <dd className="mt-1.5 text-xl text-ink-200 tabular-nums">{item.v}</dd>
                </div>
              ))}
            </dl>
          </div>

          {/* The panel, at its own aspect ratio. Not a mockup and not a render
              of a design file: the real frontend, laid out by a real browser at
              800x480, which is the size of the screen this ships on.

              LABELLED AS HARDWARE, because a bare screenshot in the right
              column of a web page reads as the web page's own app, which is the
              confusion the dice pad caused here. The strip names the board and
              the panel instead of drawing a plastic case round it (see the
              bezel note in Device.tsx). */}
          <div className="min-w-0">
            <figure className="m-0 rounded-lg border border-ink-800 bg-ink-950 overflow-hidden">
              <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 px-4 py-2.5 border-b border-ink-800 font-mono text-[0.7rem] uppercase tracking-[0.16em]">
                <span className="text-ink-300">On the device</span>
                <span className="text-ink-500">Raspberry Pi 4 &middot; 7 inch touchscreen</span>
              </div>
              <img
                src="/device/lock.png"
                alt="The device's first screen: a verified badge, the manifest root and the system partition hash, and a button to open a wallet"
                width={1600}
                height={960}
                fetchPriority="high"
                className="block w-full h-auto"
              />
            </figure>
            <p className="mt-3 text-sm text-ink-400 leading-relaxed">
              The first screen, before any wallet is open. The top hash is the software the device
              is about to run. Build the source yourself, and if your number differs, do not enter
              your PIN. Nothing on this website runs that software.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}
